tmgmt.translator.settings.mygengo:
  type: tmgmt.translator_base
  mapping:
    auto_accept:
     type: boolean
     label: Automatically accept
    mygengo_auto_approve:
      type: boolean
      label: Automatically approve jobs at Gengo side.
    api_public_key:
      type: string
      label: Gengo API Public key
    api_private_key:
      type: string
      label: Gengo API Private key
    use_sandbox:
      type: boolean
      label: Use the sandbox
    use_preferred:
      type: boolean
      label: Use preferred translators
    show_remaining_credits_info:
      type: boolean
      label: Show remaining credit info
tmgmt_mygengo.settings:
  type: config_object
  mapping:
    use_mock_service:
      type: boolean
      label: Use mock service
    tmgmt_mygengo_debug:
      type: boolean
      label: Debugging
